# @license UNLICENSED
# @copyright U IRIS. All rights reserved.
# @author Florian Daguin <florian.daguin@systeme-u.fr>

# @file yamllint configuration file.
# @see https://github.com/adrienverge/yamllint
# @see https://yamllint.readthedocs.io/en/stable/configuration.html#configuration
---
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start: disable
  empty-lines: enable
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: disable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
