name: Release
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: New release
        id: new-release
        uses: google-github-actions/release-please-action@v2.29.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
